### ISSUE TITLE
js/min/scripts-min.js throws an error when the current version of jQuery is loaded

### ISSUE THREAD

**Issue by blizam** [getgrav/grav-skeleton-boxify-site#1]
jquery-2.x.min.js:2 Uncaught Error: Syntax error, unrecognized expression: a[href*=#]:not([href=#])

error is present in Demo as well

**Comment by w00fz** [comment]
Btw for the future you should open the issue in the actual theme repo as this is just the skeleton and not really related with the issue per se.

**Comment by blizam** [comment]
gotcha, ty ty
